theme: jekyll-theme-leap-day
title: A Security Testbed for a Networked DES Control System

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5

kramdown:
   input: GFM
   hard_wrap: false
   # syntax_highlighter: rouge
